CIS hardening
octoenergy/puppet-octo_base pull request #15
Opened 2020-10-22 15:15 UTC by dooferlad

2020-10-22 15:17 UTC, dooferlad commented on manifests/cis_hardening/system.pp
> +  # 1.3.1 Ensure AIDE is installed
I think it is OK to not bother with this and list it as an exclusion. We may want to add this to the bastions, but for our usual boxes we deploy so often it isn't worth it.

If we deploy on bastions be warned that we will need a different machine type because of the CPU power requirements to hash the entire file system - it would just eat all the credits.

2020-10-22 15:20 UTC, dooferlad commented on manifests/cis_hardening/system.pp
> +  #       TODO: Should we bother?
I am interested in other people's thoughts about if /tmp, /var, /var/tmp, /var/log, /var/log/audit and /home are worth separating out into separate partitions. I get the argument (if you use up space you can DOS attack the system), but I don't know if it is valid in our case where we have no sudo password and a single user who can log in.

2020-10-23 10:14 UTC, codeinthehole requested changes
Seems fine. 

I would avoid committing lots of commented-out code, and the commit mesage could do with more explanation.

2020-10-23 10:14 UTC, codeinthehole commented on files/cis_hardening/core.conf
> +* hard core 0
Minor thing. The rough convention we've used to date is to use `files/$DESTIONATION_PATH` so this would be stored in `files/etc/security/limits.d/cores.conf`. Copying how deb files work.

2020-10-23 10:14 UTC, codeinthehole commented on manifests/cis_hardening/system.pp
> +  #  TODO: Do we actually want this? Perhaps just on bastions?
Shall we wrap in a Puppet conditional that defaults to False - then we can enable only for some machine types.

2020-10-23 10:14 UTC, codeinthehole commented on manifests/inspector/system.pp
> +  }
Does this belong in a separate commit?

2020-10-23 10:14 UTC, codeinthehole commented on manifests/cis_hardening/system.pp
> +  #       TODO: Should we bother?
Don't know sorry

2020-10-23 10:37 UTC, dooferlad commented on manifests/cis_hardening/system.pp
> +  #  TODO: Do we actually want this? Perhaps just on bastions?
Good point.

My reservation with AIDE is that we would only run it on Bastion boxes, which we will need to upgrade so they weren't restricted by CPU credits and could perform the scans without slowing down their primary purpose. We would, of course, need to add a check that AIDE is running and that the reports are OK.

My reservation with Bastion boxes is that they aren't needed if we use a VPN and we should probably just discard them and use a VPN anyway. The DB bastions have another role of course and running AIDE on them seems like a good idea. I would rather drop the DB bastions and tell clients to use zscalar though since that gives us one fewer system to worry about.

2020-10-23 10:38 UTC, dooferlad commented on manifests/inspector/system.pp
> +  }
Yes. Seems to have been squashed unreasonably.

2020-10-23 10:41 UTC, dooferlad commented on files/cis_hardening/core.conf
> +* hard core 0
> Seems fine.
> 
> I would avoid committing lots of commented-out code, and the commit mesage could do with more explanation.

Agreed. The commented out code is there to hang a conversation off and I intend on either dropping it or using it. The commit message is rubbish and I will fix it.

2020-10-23 14:03 UTC, dooferlad commented on manifests/cis_hardening/system.pp
> +  #  TODO: Do we actually want this? Perhaps just on bastions?
I have left it out for now

2020-10-26 16:38 UTC, storeyio commented on manifests/cis_hardening/system.pp
> +  #       TODO: Should we bother?
I believe this is on the back of another requirement that says /tmp, /var/tmp and /var/log need noexec and nodev mount options; what's our status with those?

What does our audit.conf look like? I'm more familiar with CentOS but I recall the defaults will halt the system if the audit process can't write any more logs.

2020-10-27 12:09 UTC, dooferlad commented on manifests/cis_hardening/system.pp
> +  #       TODO: Should we bother?
We don't run auditd, which solves a few of those problems.

The reason for noexec (I didn't recall nodev being a recommendation) is to prevent someone getting onto the system and dropping an executable into, for example, /tmp. For single user systems where that single user has passwordless sudo I don't think we should care about /tmp since they could put a binary anywhere they like and, should they wish, remount /tmp with different permissions.

2020-10-27 15:02 UTC, storeyio commented on manifests/cis_hardening/system.pp
> +  #       TODO: Should we bother?
I think 1.1.3 is the nodev requirement for /tmp ?

Oh yeah, I understand why the noexec requirement exists - presumably nginx isn't running as root/ubuntu? I would guess it's designed to mitigate instances where the nginx user is the entrypoint (usually to /tmp as all users can write to it by default).

2020-10-28 09:52 UTC, codeinthehole approved these changes
Looks good. Let's try it out

2020-10-28 09:52 UTC, codeinthehole commented on Puppetfile.lock
> +  puppetlabs-stdlib (>= 2.0.0)
Are you sure we need this file? I'm confused about why we've never needed it before

2020-10-29 13:44 UTC, dooferlad commented on Puppetfile.lock
> +  puppetlabs-stdlib (>= 2.0.0)
Ah, bother, my mistake. Will remove it.

2020-10-30 10:26 UTC, merged