Batch cloudwatch metrics upload to reduce cpu usage
octoenergy/puppet-octo_base pull request #25
Opened 2021-02-03 05:22 UTC by sammaritan12

Additionally did some auto-formatting in vscode

https://app.asana.com/0/1163919217444318/1199567924494792/f

2021-02-22 09:55 UTC, dooferlad requested changes
Thanks for the PR!

Please remove the non-functional changes, since these just increase diff noise and make it harder to discern what the important changes are when looking back through the git history. Other than that, it looks good.

2021-02-22 10:10 UTC, sammaritan12 commented
@dooferlad all good, I use format on save in my IDE and it seemed to be overzealous in the formatting this time :)

2021-02-22 11:09 UTC, dooferlad commented on files/cloudwatch/metrics.json
> +                "Value": $INSTANCE_NAME
Why instance name, but not ID?

2021-02-22 11:09 UTC, dooferlad commented on files/cloudwatch/metrics.json
> +                "Value": $INSTANCE_ID
Why instance ID, but not name?

2021-02-22 11:10 UTC, dooferlad reviewed
Just a couple of questions about why we sometimes have instance IDs, other times instance names, and other times both. I would think that, if possible, having names and IDs would be best.

2021-02-22 23:44 UTC, sammaritan12 commented on files/cloudwatch/metrics.json
> +                "Value": $INSTANCE_NAME
This was just a migration from single calls to a batched call, the original code didn't have Instance ID, so I didn't include it. If you think it's reasonable to add I can definitely add it.

```sh
$AWS_EXECUTABLE --region=$REGION cloudwatch put-metric-data --namespace $NAMESPACE --metric-name "CPUUtilization" --unit "Percent" --value $CPU --dimensions "InstanceName=$INSTANCE_NAME" --timestamp $TIMESTAMP
```

2021-02-22 23:44 UTC, sammaritan12 commented on files/cloudwatch/metrics.json
> +                "Value": $INSTANCE_ID
As above, but with the following code

```sh
$AWS_EXECUTABLE --region=$REGION cloudwatch put-metric-data --namespace $NAMESPACE --metric-name "MemoryUsed" --unit "Megabytes" --value $MEMORY_USED --dimensions "InstanceId=$INSTANCE_ID" --timestamp $TIMESTAMP

```

2021-03-02 10:11 UTC, dooferlad approved these changes

2021-03-25 03:49 UTC, sammaritan12 commented
Am merging, only things changed is the shell substitution didn't work in the `jq` command so I had to put the filename explicitly. Additionally I'm passing in a file to the AWS CLI because for some reason part of the bash prompt ends up in the variable.

2021-03-25 03:50 UTC, merged